In [ ]:

import pandas as pd


In [ ]:

cs = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Concrete%20Compressive%20Strength.csv')

In [ ]:
cs.head()

Cement (kg in a m^3 mixture)  Blast Furnace Slag (kg in a m^3 mixture)  \
0                         540.0                                       0.0   
1                         540.0                                       0.0   
2                         332.5                                     142.5   
3                         332.5                                     142.5   
4                         198.6                                     132.4   

   Fly Ash (kg in a m^3 mixture)  Water (kg in a m^3 mixture)  \
0                            0.0                        162.0   
1                            0.0                        162.0   
2                            0.0                        228.0   
3                            0.0                        228.0   
4                            0.0                        192.0   

   Superplasticizer (kg in a m^3 mixture)  \
0                                     2.5   
1                                     2.5   
2                                     0.0   
3                                     0.0   
4                                     0.0   

   Coarse Aggregate (kg in a m^3 mixture)  \
0                                  1040.0   
1                                  1055.0   
2                                   932.0   
3                                   932.0   
4                                   978.4   

   Fine Aggregate (kg in a m^3 mixture)  Age (day)  \
0                                 676.0         28   
1                                 676.0         28   
2                                 594.0        270   
3                                 594.0        365   
4                                 825.5        360   

   Concrete Compressive Strength(MPa, megapascals)   
0                                         79.986111  
1                                         61.887366  
2                                         40.269535  
3                                         41.052780  
4                                         44.296075

In [ ]:
cs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column                                            Non-Null Count  Dtype  
---  ------                                            --------------  -----  
 0   Cement (kg in a m^3 mixture)                      1030 non-null   float64
 1   Blast Furnace Slag (kg in a m^3 mixture)          1030 non-null   float64
 2   Fly Ash (kg in a m^3 mixture)                     1030 non-null   float64
 3   Water (kg in a m^3 mixture)                       1030 non-null   float64
 4   Superplasticizer (kg in a m^3 mixture)            1030 non-null   float64
 5   Coarse Aggregate (kg in a m^3 mixture)            1030 non-null   float64
 6   Fine Aggregate (kg in a m^3 mixture)              1030 non-null   float64
 7   Age (day)                                         1030 non-null   int64  
 8   Concrete Compressive Strength(MPa, megapascals)   1030 non-null   float64
dtypes: float64(8), int64

In [ ]:
cs.describe()

Cement (kg in a m^3 mixture)  Blast Furnace Slag (kg in a m^3 mixture)  \
count                   1030.000000                               1030.000000   
mean                     281.165631                                 73.895485   
std                      104.507142                                 86.279104   
min                      102.000000                                  0.000000   
25%                      192.375000                                  0.000000   
50%                      272.900000                                 22.000000   
75%                      350.000000                                142.950000   
max                      540.000000                                359.400000   

       Fly Ash (kg in a m^3 mixture)  Water (kg in a m^3 mixture)  \
count                    1030.000000                  1030.000000   
mean                       54.187136                   181.566359   
std                        63.996469                    21.355567   
min                         0.000000                   121.750000   
25%                         0.000000                   164.900000   
50%                         0.000000                   185.000000   
75%                       118.270000                   192.000000   
max                       200.100000                   247.000000   

       Superplasticizer (kg in a m^3 mixture)  \
count                             1030.000000   
mean                                 6.203112   
std                                  5.973492   
min                                  0.000000   
25%                                  0.000000   
50%                                  6.350000   
75%                                 10.160000   
max                                 32.200000   

       Coarse Aggregate (kg in a m^3 mixture)  \
count                             1030.000000   
mean                               972.918592   
std                                 77.753818   
min                                801.000000   
25%                                932.000000   
50%                                968.000000   
75%                               1029.400000   
max                               1145.000000   

       Fine Aggregate (kg in a m^3 mixture)    Age (day)  \
count                           1030.000000  1030.000000   
mean                             773.578883    45.662136   
std                               80.175427    63.169912   
min                              594.000000     1.000000   
25%                              730.950000     7.000000   
50%                              779.510000    28.000000   
75%                              824.000000    56.000000   
max                              992.600000   365.000000   

       Concrete Compressive Strength(MPa, megapascals)   
count                                       1030.000000  
mean                                          35.817836  
std                                           16.705679  
min                                            2.331808  
25%                                           23.707115  
50%                                           34.442774  
75%                                           46.136287  
max                                           82.599225

In [ ]:
cs.columns

Index(['Cement (kg in a m^3 mixture)',
       'Blast Furnace Slag (kg in a m^3 mixture)',
       'Fly Ash (kg in a m^3 mixture)', 'Water (kg in a m^3 mixture)',
       'Superplasticizer (kg in a m^3 mixture)',
       'Coarse Aggregate (kg in a m^3 mixture)',
       'Fine Aggregate (kg in a m^3 mixture)', 'Age (day)',
       'Concrete Compressive Strength(MPa, megapascals) '],
      dtype='object')

In [ ]:
X = cs[['Cement (kg in a m^3 mixture)',
       'Blast Furnace Slag (kg in a m^3 mixture)',
       'Fly Ash (kg in a m^3 mixture)', 'Water (kg in a m^3 mixture)',
       'Superplasticizer (kg in a m^3 mixture)',
       'Coarse Aggregate (kg in a m^3 mixture)',
       'Fine Aggregate (kg in a m^3 mixture)', 'Age (day)']]

In [ ]:
y = cs['Concrete Compressive Strength(MPa, megapascals) ']

In [ ]:
X.shape

(1030, 8)

In [ ]:
y.shape

(1030,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=2529)

In [ ]:
X_train.shape, X_test.shape , y_train.shape, y_test.shape

((721, 8), (309, 8), (721,), (309,))

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.predict(X_test)

array([32.9126838 , 29.49103627, 51.22744988, 30.72830892, 61.01296607,
       36.1860749 , 18.19613228, 26.67718822, 31.39625583, 45.79720573,
       27.01819052, 22.39021356, 58.90321481, 44.06988109, 18.33538005,
       52.04886033, 36.49614143, 22.60633035, 30.30663022, 31.18479226,
       27.89909444, 32.26166347, 36.44587199, 31.20297845, 32.16141073,
       31.42165654, 44.72420225, 40.86127394, 73.03848849, 38.1254862 ,
       40.46367612, 49.81062665, 14.41496407, 61.79729246, 50.64223527,
       41.04723247, 27.55227895, 25.95109489, 41.91398869, 36.47050866,
       68.71688125, 21.52022469, 50.64223527, 34.38615155, 33.98783598,
       23.2595543 , 27.43079038, 63.57584523, 61.7732999 , 36.71417786,
       33.12177958, 39.83037545, 24.30184486, 53.62147764, 31.66355469,
       48.4918046 , 44.42143815, 23.85939922, 50.55499844, 54.17541752,
       28.12522197, 48.10148132, 56.81515762, 50.11038048, 36.31278417,
       32.89852959, 53.07186634, 16.60411502, 24.9233279 , 20.59

In [ ]:
model.intercept_

9.091564943904963

In [ ]:
model.coef_

array([ 0.10993242,  0.09405068,  0.08143475, -0.21109854,  0.24127402,
        0.00874882,  0.00890343,  0.1329637 ])

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error,mean_absolute_error,mean_squared_error

In [ ]:
mean_absolute_percentage_error(y_test,y_pred)

0.3134440184320867

In [ ]:
mean_absolute_error(y_test,y_pred)

8.683767775410708

In [ ]:
mean_squared_error(y_test,y_pred)

120.40313453787677

In [ ]:
y_test

639    43.698989
992    15.423578
363    63.528319
421    34.239378
26     41.151375
         ...    
620    29.785363
17     56.141962
632    30.571366
918    10.535193
225    17.822955
Name: Concrete Compressive Strength(MPa, megapascals) , Length: 309, dtype: float64

In [ ]:
model.score(X_test,y_test)

0.5546299611165384

In [ ]:

X_test.head(1)



Cement (kg in a m^3 mixture)  Blast Furnace Slag (kg in a m^3 mixture)  \
639                         400.0                                       0.0   

     Fly Ash (kg in a m^3 mixture)  Water (kg in a m^3 mixture)  \
639                            0.0                        187.0   

     Superplasticizer (kg in a m^3 mixture)  \
639                                     0.0   

     Coarse Aggregate (kg in a m^3 mixture)  \
639                                  1025.0   

     Fine Aggregate (kg in a m^3 mixture)  Age (day)  
639                                 745.0         28

In [ ]:
model.predict(X_test.iloc[0].values.reshape(1,-1))

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([32.9126838])